DROP TABLE NAMES CASCADE CONSTRAINTS;            
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE BOOKINGDETAIL CASCADE CONSTRAINTS;
DROP TABLE BOOKINGS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE PHONENUMBER CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTATION CASCADE CONSTRAINTS;
DROP TABLE PROMOTION CASCADE CONSTRAINTS;
DROP TABLE BRANCH CASCADE CONSTRAINTS;
DROP TABLE NAME CASCADE CONSTRAINTS;
DROP TABLE GIFTCARD CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;
DROP TABLE MEMBERSHIP CASCADE CONSTRAINTS;
DROP TABLE PACKAGETOUR CASCADE CONSTRAINTS;
DROP TABLE PAYMENTTRANSACTION CASCADE CONSTRAINTS;
DROP TABLE SALESPERSON CASCADE CONSTRAINTS;

